name: ambilytics
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/maxim-saplin/ambilytics

environment:
  sdk: ^3.0.5
  flutter:

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  shared_preferences: 2.2.0
  uuid:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
