name: ambilytics
description: Google Analytics for all Flutter platforms (Android, iOS, macOS, Web, Windows and Linux)
version: 1.1.0
repository: https://github.com/maxim-saplin/ambilytics
homepage: https://github.com/maxim-saplin/ambilytics

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  firebase_analytics: ^11.2.1
  firebase_core: ^3.10.1
  shared_preferences: ^2.5.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

false_secrets:
  - example/*